### ISSUE TITLE
Failed to load the es-navigation package

### ISSUE THREAD

**Issue by konistehrad** [incrementallair/es-navigation#18]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.187.0
**System**: Mac OS X 10.10.2
**Thrown From**: [es-navigation](https://github.com/incrementallair/es-navigation) package, v0.1.5
### Stack Trace

Failed to load the es-navigation package

```
At Cannot find module 'escope'

Error: Cannot find module 'escope'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app/src/module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/Users/conrad/.atom/packages/es-navigation/build/parse.js:13:29)
    at Module._compile (module.js:475:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:370:32)
    at Function.Module._load (module.js:325:12)
```
### Commands

```
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.2.3
es-navigation, v0.1.5
language-jade, v0.3.0

# Dev
No dev packages
```

**Comment by mikewoudenberg** [comment]
Running `npm install && gulp build` in the ~/.atom/packages/es-navigation/node_modules/escope folder fixes the problem. But it's an ugly workaround.

**Comment by konistehrad** [comment]
Good to know tho, thank you!

**Comment by seawatts** [comment]
Is there a longer term solution for this? If not maybe we should put this on the readme.

**Comment by malko** [comment]
gulp build doesn't work here:

```
$ gulp build
[09:37:56] Using gulpfile ~/.atom/packages/es-navigation/gulpfile.js
[09:37:56] Task 'build' is not in your gulpfile
[09:37:56] Please check the documentation for proper gulpfile formatting
```

**Comment by camel-chased** [comment]
same here

**Comment by timaschew** [comment]
I get this error on when installing the package

`Cannot read property 'prototype' of undefined`

``` js
TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/anton/.atom/packages/es-navigation/build/status-bar.js:13:26)
    at /Users/anton/.atom/packages/es-navigation/build/status-bar.js:20:3
    at Object.<anonymous> (/Users/anton/.atom/packages/es-navigation/build/status-bar.js:45:3)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/anton/.atom/packages/es-navigation/build/view.js:42:43)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/anton/.atom/packages/es-navigation/build/main.js:4:25)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/anton/.atom/packages/es-navigation/build/index.js:3:12)
    at Module._compile (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:721:27)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:117:28
    at Package.module.exports.Package.measure (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/package-manager.js:524:30)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:444:29
    at exit (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
    at triggerExitCallback (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at ChildProcess.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/buffered-process.js:235:18)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
```

**Comment by PointedEars** [comment]
1. Start Atom

**Atom Version**: 1.5.3
**System**: Debian GNU/Linux
**Thrown From**: [es-navigation](https://github.com/incrementallair/es-navigation) package, v0.1.5

### Stack Trace

Failed to load the es-navigation package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/usr/local/atom/packages/es-navigation/build/status-bar.js:13:26)
    at /usr/local/atom/packages/es-navigation/build/status-bar.js:20:3
    at Object.<anonymous> (/usr/local/atom/packages/es-navigation/build/status-bar.js:45:3)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/es-navigation/build/view.js:42:43)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/es-navigation/build/main.js:4:25)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/es-navigation/build/index.js:3:12)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .js] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
  4x -2:13.3.0 blur (atom-text-editor.editor.is-focused.vim-mode-plus.normal-mode)
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view"
    ]
  }
}
```

### Installed Packages

``` coffee
# User
atom-htmltidy, v2.3.0
atom-ternjs, v0.13.2
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.21.0
autocomplete-awk, v0.1.2
autocomplete-bibtex, v0.6.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.6.1
autocomplete-xml, v0.8.2
autoupdate-packages, v1.3.1
branch-status, v0.8.1
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.1.1
column-select, v0.2.0
compare-files, v0.6.2
css-snippets, v0.9.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
es-navigation, v0.1.5
file-icons, v1.6.15
filesize, v0.4.2
git-diff-details, v0.23.0
git-go, v1.0.1
git-grep, v0.9.0
git-hide, v0.1.2
git-log, v0.4.1
git-tabs, v0.3.0
highlight-selected, v0.11.2
hyperclick-php, v0.2.1
javascript-snippets, v1.2.1
js-hyperclick, v1.4.1
js-refactor, v0.6.0
keyboard-localization, v1.4.15
language-apache, v1.4.0
language-diff, v0.4.0
language-gettext, v0.6.1
language-latex, v0.6.1
language-sql-mysql, v0.3.1
latex, v0.29.0
latexer, v0.3.0
line-count-status, v0.0.3
line-jumper, v0.14.1
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-chktex, v1.2.5
linter-csslint, v1.3.1
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-less, v2.4.2
linter-mixed-indent, v1.1.0
linter-php, v1.1.8
linter-pylint, v1.2.0
linter-shellcheck, v1.1.0
linter-xmllint, v1.3.4
local-history, v3.2.3
method-separator, v0.1.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
nav-panel, v0.0.11
navigate, v0.1.13
navigate-indent, v0.1.0
nuclide, v0.118.0
open-recent, v5.0.0
php-debug, v0.2.2
php-extract-method, v0.2.1
php-getters-setters, v0.5.5
pigments, v0.24.1
project-view, v0.5.0
punchclock, v0.6.5
python-isort, v0.0.7
python-tools, v0.6.7
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.2
remote-edit, v1.8.24
revert-buffer, v0.5.0
svn, v0.0.9
symbols-tree-view, v0.11.0
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.3
up2date, v0.1.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.21.3
w3c-validation, v0.4.0
xkcd-comics, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by nickpresta** [comment]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [es-navigation](https://github.com/incrementallair/es-navigation) package, v0.1.5

### Stack Trace

Failed to load the es-navigation package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/Users/nickpresta/.atom/packages/es-navigation/build/status-bar.js:13:26)
  at /Users/nickpresta/.atom/packages/es-navigation/build/status-bar.js:20:3
  at Object.<anonymous> (/Users/nickpresta/.atom/packages/es-navigation/build/status-bar.js:45:3)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/nickpresta/.atom/packages/es-navigation/build/view.js:42:43)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/nickpresta/.atom/packages/es-navigation/build/main.js:4:25)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Object.<anonymous> (/Users/nickpresta/.atom/packages/es-navigation/build/index.js:3:12)
  at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
  at Object.defineProperty.value [as .js] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Module.require (module.js:366:17)
  at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
  at Package.module.exports.Package.requireMainModule (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:715:27)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:117:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
  at Package.module.exports.Package.load (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:106:12)
  at PackageManager.module.exports.PackageManager.loadPackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:457:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:536:30)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:452:29
  at exit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/settings-view/lib/package-manager.js:73:16)
  at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
  at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
  at emitOne (events.js:82:20)
  at Socket.emit (events.js:169:7)
  at Pipe._onclose (net.js:469:12)

```

### Commands

```
     -1:39.1.0 jump-to-import:go-to-module (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  3x -1:38.6.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
  7x -1:34.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:33.8.0 vim-mode:move-right (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:32.7.0 jump-to-import:go-to-module (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:31.8.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:31.7.0 vim-mode:move-up (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:29.5.0 vim-mode:insert-after (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -1:28.1.0 jump-to-import:go-to-module (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:26.8.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -1:26.6.0 vim-mode:reset-normal-mode (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:47.3.0 command-palette:toggle (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:45 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:44.8.0 settings-view:uninstall-packages (atom-text-editor.editor.vim-mode.normal-mode)
  2x -0:28.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```

### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig",
        "BUCK.autodeps"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "linter",
      "tree-view",
      "atom-ternjs"
    ],
    "projectHome": "/Users/nickpresta/src"
  }
}
```

### Installed Packages

``` coffee
# User
es-navigation, v0.1.5
linter-eslint, v7.2.4
nuclide, v0.158.0
react, v0.15.0
vim-mode, v0.65.1

# Dev
No dev packages
```
