### ISSUE TITLE
Failed to load es-navigation package in 0.192.0

### ISSUE THREAD

**Issue by Globegitter** [incrementallair/es-navigation#19]
A new version a new error:

[Enter steps to reproduce below:]

1.

**Atom Version**: 0.192.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [es-navigation](https://github.com/incrementallair/es-navigation) package, v0.1.5
### Stack Trace

Failed to load the es-navigation package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/Users/markus/.atom/packages/es-navigation/build/status-bar.js:13:26)
    at /Users/markus/.atom/packages/es-navigation/build/status-bar.js:20:3
    at Object.<anonymous> (/Users/markus/.atom/packages/es-navigation/build/status-bar.js:45:3)
    at Module._compile (module.js:452:26)
    at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
    at Module.load (module.js:347:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/Users/markus/.atom/packages/es-navigation/build/view.js:42:43)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view",
      "language-sass",
      "linter-eslint",
      "linter"
    ],
    "excludeVcsIgnoredPaths": false
  }
}
```
### Installed Packages

``` coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
auto-indent, v0.1.0
better-handlebars, v0.1.1
color-picker, v1.6.0
editor-stats, v0.17.0
emmet, v2.3.7
es-navigation, v0.1.5
indent-guide-ext, v0.1.0
language-docker, v1.1.3
language-javascript-better, v1.3.0
language-json5, v1.1.0
sublime-tabs, v0.5.3

# Dev
No dev packages
```

**Comment by seawatts** [comment]
Also getting this same error. Is there a fix?

**Comment by guybedford** [comment]
Thanks, this project is no longer actively maintained unfortunately. If you're interested in helping out and becoming a maintainer you are more than welcome.
