### ISSUE TITLE
Failed to load the es-navigation package

### ISSUE THREAD

**Issue by cboulanger** [incrementallair/es-navigation#24]
[Enter steps to reproduce:]

1. Install es-navigation package

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [es-navigation](https://github.com/incrementallair/es-navigation) package 0.1.5

### Stack Trace

Failed to load the es-navigation package

```
At Cannot read property 'prototype' of undefined

TypeError: Cannot read property 'prototype' of undefined
    at __extends (/packages/es-navigation/build/status-bar.js:13:26)
    at /packages/es-navigation/build/status-bar.js:20:3
    at /packages/es-navigation/build/status-bar.js:45:3)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/es-navigation/build/view.js:42:175)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/es-navigation/build/main.js:4:42)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/es-navigation/build/index.js:3:12)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
```

### Commands

```
```

### Non-Core Packages

```
api-docs 0.0.6 
atom-beautify 0.29.17 
atom-ternjs 0.18.2 
autocomplete-xml 0.9.4 
busy-signal 1.3.0 
docblockr 0.9.3 
es-navigation 0.1.5 
intentions 1.1.2 
js-refactor 0.7.5 
linter 2.1.0 
linter-jshint 3.0.3 
linter-ui-default 1.2.1 
nav-panel 0.0.11 
node-debugger 1.10.1 
refactor 0.11.3 
tag 0.4.0 
```

**Comment by DanielKolsi** [comment]
I had the same problem. Had to disable that package.

**Comment by jdsharp** [comment]
I also experienced this issue... _(uninstalled)_
